DiamondLightSource/python-copier-template

template/catalog-info.yaml
allows for discovery after the componment has been created
=> added catalog-info.yaml

catalog-info.yaml
If not signed in as the GitHub user of where you want the repo to be created, it will prompt you to sign in
=> Auth requirement and tokens for creating a new GitHub project

docs/explanations/decisions/0001-record-architecture-decisions.rst, template/{% if docs_type=="sphinx" %}docs{% endif %}/developer/explanations/decisions/0001-record-architecture-decisions.rst, template/{% if docs_type=="sphinx" %}docs{% endif %}/developer/explanations/decisions/0002-switched-to-pip-skeleton.rst.jinja
=> Removed dates from ADRs

template/{% if docs_type=="sphinx" %}docs{% endif %}/conf.py.jinja
=> fix switcher_json variable replacement

copier.yml
=> set default for component owner

template/pyproject.toml.jinja
=> added 'copier' to dev dependencies

.github/workflows/_check.yml, .github/workflows/ci.yml, template/{% if git_platform=="github.com" %}.github{% endif %}/workflows/ci.yml.jinja
Fix bug where it was always excluding PRs
=> Fix branch PR check logic

template/{% if sphinx %}docs{% endif %}/conf.py.jinja
don't use jinja to template; instead use f-strings at build time
resolves #69
=> reverted 84a7736

docs/conf.py, docs/explanations/decisions/0008-use-tox.md, docs/reference/standards.rst, template/.vscode/settings.json.jinja, template/pyproject.toml.jinja, template/{% if git_platform=="github.com" %}.github{% endif %}/workflows/ci.yml.jinja, template/{% if sphinx %}docs{% endif %}/conf.py.jinja, template/{% if sphinx %}docs{% endif %}/developer/how-to/static-analysis.rst, template/{% if sphinx %}docs{% endif %}/developer/reference/standards.rst
=> Use pyright instead of mypy

.devcontainer/devcontainer.json, template/README.md.jinja, template/pyproject.toml.jinja, tests/test_example.py
Also add a test for this
Fixes #57
=> Remove docs tox env if sphinx not selected

example-answers.yml, template/README.md.jinja, tests/test_example.py
This makes the example repo more readable on PyPI
Also fix test that updates example to use answers from example-answers.yml
=> Use description in README and update example description

docs/conf.py, template/{% if sphinx %}docs{% endif %}/conf.py.jinja, template/{% if sphinx %}docs{% endif %}/reference.md.jinja
From top bar to reference section
Fixes #97
=> Move release notes

docs/tutorials/adopt-existing.md
=> added adopting template docs

copier.yml, tests/test_example.py
=> Allow dots in repo names

template/pyproject.toml.jinja, tests/test_example.py
=> Add mypy dependency to pyproject.toml if selected

docs/how-to/dev-install.md
The constraints.txt file was removed in #43.
=> Update developer environment install instructions

README.md, copier.yml, docs/how-to/dev-install.md, docs/tutorials/create-new.md
Fixes #128, partially fixes #117
=> Documentation tweaks

.github/pages/make_switcher.py, docs/conf.py, template/{% if sphinx %}docs{% endif %}/conf.py.jinja
=> Fix docs issues with org level sites

.github/pages/make_switcher.py, README.md, docs/how-to/dev-install.md, docs/tutorials/installation.md, pyproject.toml, template/pyproject.toml.jinja, template/{% if git_platform=="github.com" %}.github{% endif %}/workflows/ci.yml.jinja, template/{% if sphinx %}docs{% endif %}/tutorials/installation.md.jinja, tests/test_example.py
Test adoption [here](https://github.com/DiamondLightSource/FastCS/pull/27) (with 3.12 removed because it doesn't work in the project yet).
Fixes #63 
Fixes #139
=> Update minimum python version to 3.10

template/Dockerfile.jinja, template/README.md.jinja
Now it will make sure there is not a blank line at the end
=> Fix Dockerfile and README templates end of file

template/Dockerfile.jinja
As discovered in https://github.com/DiamondLightSource/blueapi/pull/499
=> Use dev-requirements.txt in the Dockerfile

docs/how-to/strict-mode.md, template/src/{{ package_name }}/__main__.py.jinja, tests/conftest.py, tests/test_example.py
=> Ensure template works with pright in strict mode

docs/how-to/update-template.md
- Fix command in docs for updating the template
- Briefly expand upon finding and resolving merge conflicts during updates
=> Expand updating docs

Dockerfile, template/Dockerfile.jinja
Tests will pass after #203 merged
Fixes #200
=> Match casing of AS and FROM in Dockerfile
