DiamondLightSource/python-copier-template

catalog-info.yaml, template/README.rst.jinja, template/pyproject.toml.jinja, template/src/{{package_name}}/__init__.py.jinja, template/{% if docker_containers==true %}Dockerfile{% endif %}.jinja, template/{% if docs_option==true %}docs{% endif %}/conf.py.jinja, template/{% if docs_option==true %}docs{% endif %}/user/tutorials/installation.rst.jinja, template/{% if git_platform=='GitHub' %}.github{% endif %}/CONTRIBUTING.rst.jinja, template/{% if git_platform=='GitHub' %}.github{% endif %}/actions/install_requirements/action.yml, template/{% if git_platform=='GitHub' %}.github{% endif %}/dependabot.yml, template/{% if git_platform=='GitHub' %}.github{% endif %}/workflows/code.yml, template/{% if git_platform=='GitHub' %}.github{% endif %}/workflows/docs.yml, template/{% if git_platform=='GitHub' %}.github{% endif %}/workflows/linkcheck.yml
Included changes from skeleton PRs [#161](
https://github.com/DiamondLightSource/python3-pip-skeleton/pull/161), [#162](
https://github.com/DiamondLightSource/python3-pip-skeleton/pull/162) and [#163](
https://github.com/DiamondLightSource/python3-pip-skeleton/pull/163)
Changed some variables in the template
=> Fixing variables and new updated differences from the pip-skeleton

README.md
Update README with correct usage info:
- Add `--trust` CLI argument which is required to run the `git init` task
- Remove `$` from CLI instructions so they can be copy/pasted wholesale into the terminal
=> Update usage instructions in README

template/{% if git_platform=="github.com" %}.github{% endif %}/workflows/code.yml
If the dist_name precedes package name alphabetically then it would pick the .egg-info
file instead of the src directory. Exclude this
=> Fix dist job where dist_name != package_name

.github/workflows/_docs.yml, .github/workflows/_example.yml, .github/workflows/ci.yml, example-answers.yml, tests/test_example.py
This keeps python-copier-template-example up to date whenever python-copier-template has a push to main
=> Add example publishing

copier.yml
Set the default Github org to DiamondLightSource, this is an opinioned template and the 80% use case will be DiamondLightSource, so may as well streamline it without precluding other orgs.
=> Make a default Github org

pyproject.toml, template/pyproject.toml.jinja
The warning was
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`: - 'select' -> 'lint.select'
```
=> Fix ruff config deprecation warning

.github/workflows/_test.yml, .github/workflows/ci.yml, template/{% if git_platform=="github.com" %}.github{% endif %}/workflows/ci.yml.jinja, template/{% if sphinx %}docs{% endif %}/developer/how-to/coverage.md
=> Update codecov action to v4

template/{% if git_platform=="github.com" %}.github{% endif %}/CONTRIBUTING.md.jinja
This links to the correct version of the dev docs in the contributing guide
Fixes #96
=> Add link to template how-to guides in contributing.md

tests/test_example.py
If we tag an existing commit that has been pushed to main, then the copier update on the old commit id will be generated with the new tag name, which means the link will not be updated. As this only affects the example repo which is the only thing that points to main then we ignore it
=> Fix example updating test

template/.gitignore, tests/test_example.py
Otherwise we get:
warning: unable to access 'template/.gitignore': Too many levels of symbolic links
Add a test to make sure the root and template .gitignores are the same
=> Make template .gitignore a file

.github/workflows/_test.yml, docs/how-to/coverage.md, docs/how-to/run-tests.md, docs/how-to/static-analysis.md, pyproject.toml, template/pyproject.toml.jinja, template/{% if git_platform=="github.com" %}.github{% endif %}/workflows/ci.yml.jinja
Allows us to switch between pyright and mypy without changing CI and the commands people type
=> Rename tox envs by task not technology

catalog-info.yaml
No longer copies the whole repo into a temp directory for copier to run on.
Copier will run directly using the latest tagged repo as it's source
Gives the _commit and correct _src_path which hence allows for updates to the project in the future
Fixes #118
=> Change fetch location to absolute url

.vscode/launch.json, template/tests/conftest.py, tests/conftest.py
Pytest nicely catches raised exceptions during tests and reports them at the end. This is very useful except when debugging tests in vscode because it prevents the debugger from pausing when there is an exception and displaying the call stack.
This adds hooks for pytest to re-raise the caught exceptions when an environment variable is set, and then sets that environment variable in the `Debug Unit Test` launch configuration.
This is currently used in [pvi](https://github.com/epics-containers/pvi).
=> Add pytest configuration for break on exception

README.md, docs/conf.py, template/{% if sphinx %}docs{% endif %}/conf.py.jinja
Remove PyPI button from docs as this project is not published to PyPI.
Fixes #137.
=> Replace references to skeleton with copier template

tests/test_example.py
In the current version of copier the type has been changed.
Fixes #144.
=> Update exception type in test_bad_repo_name

template/{% if git_platform=="github.com" %}.github{% endif %}/workflows/ci.yml.jinja
This is required to allow the workflow job to checkout the code, currently we're getting around this because our repos are public
=> Add `contents:read` permission to container workflow

template/{% if git_platform=="github.com" %}.github{% endif %}/ISSUE_TEMPLATE/bug_report.md, template/{% if git_platform=="github.com" %}.github{% endif %}/ISSUE_TEMPLATE/issue.md, template/{% if git_platform=="github.com" %}.github{% endif %}/PULL_REQUEST_TEMPLATE/pull_request_template.md
Fixes #159 
Add Issue and PR templates based on
https://github.com/DiamondLightSource/dodal, but genercised slightly. Stick with dodal's simplistic ethos rather than have many prescriptive headings and sections, instead prompting the user to put useful information in the most appropriate place for them
=> Add Issue and PR Templates

docs/explanations/decisions/0018-forbid-private-member-access-in-prod.md, template/pyproject.toml.jinja, tests/test_example.py
Fixes #154 
- Enable SLF001, forbidding private member access in src directory.
- Per discussion in #154, ignore private member access violations in tests directory
- Add test proving that ruff flags the violations
=> Enable SLF001 for src

template/pyproject.toml.jinja
This changed in v8.0.0 via https://github.com/pypa/setuptools_scm/pull/870
=> Replace deprecated write_to with version_file

.github/workflows/_container.yml
First applied [here](https://github.com/DiamondLightSource/eiger-fastcs/pull/42) to fix after #177 merged.
=> Workaround build-push-action download-artifact incompatibility

docs/how-to/dev-install.md
Add more detail on devcontainers to docs:
- Link to DLS-specific instructions
- Explain how to start the devcontainer by running vscode
- Add the devcontainer extension as a prerequisite
=> Add more detail on devcontainers to docs

copier.yml, example-answers.yml, template/catalog-info.yaml.jinja, tests/test_example.py
=> 181 fix catalog info template

.github/pages/make_switcher.py, docs/how-to/check-docs-style.md, template/src/{{ package_name }}/__main__.py.jinja, template/{% if sphinx %}docs{% endif %}/conf.py.jinja, tests/test_example.py
This updates the produced files to be compatible with pydocstyle rules and gives instructions on how to turn on checking
=> Allow pydocstyle ruff rules without enabling them

pyproject.toml
As https://github.com/copier-org/copier/issues/1819 is released as 9.4.1
This reverts commit c8b2891a5aff627a63ef14a9491050891e195f8a.
=> Uncap copier

.github/workflows/_pypi.yml
This has already been shown to fix release in pandablocks-ioc and ophyd-async.
=> set attestations to false in pypi release ci

.devcontainer/devcontainer.json
Use Richard Cunningham's lightweight bash-config feature instead of common utils.
The rebuild container overhead for this is approx 10 secs as opposed to 40-60 secs according to https://github.com/DiamondLightSource/python-copier-template/issues/208#issuecomment-2456876823
See below for details on what this feature does
https://github.com/DiamondLightSource/devcontainer-features/blob/main/.devcontainer/features/bash-config/README.md
=> switch from common-utils feature to bash-config

copier.yml, docs/how-to/strict-mode.md, example-answers.yml, template/pyproject.toml.jinja, tests/test_example.py
=> 233 strict typing

docs/explanations/decisions/0020-support-devcontainers.md, docs/how-to/dev-install.md
We have unofficially been opinionated about devcontainers for a few months now, and have been directing support requests from people using venvs to start by making one. Since supporting devcontainers is now a matter of policy in all-but-name, it should be documented and referred to in future.
=> Drop support for developing in a local venv in favour of devcontainers

README.md, docs/how-to/dev-install.md, docs/tutorials/installation.md, pyproject.toml, template/pyproject.toml.jinja, template/{% if git_platform=="github.com" %}.github{% endif %}/workflows/ci.yml.jinja, template/{% if sphinx %}docs{% endif %}/tutorials/installation.md.jinja
=> Spec-0 Add support for Python 3.13 and remove for Python 3.10

.github/dependabot.yml, .github/workflows/pr.yml, docs/explanations/decisions/0021-conventional-commits.md, docs/explanations/decisions/0022-spec-0.md
Closes #254 
Enforces conventional commit messages on this repository, to allow greater automation of change logs, releases etc.
=> ci: Enforce Conventional Commit PR titles

.github/actions/install_requirements/action.yml
When PYTHON_VERSION is pinned to a specific sha (as done by Renovate best-practices), install_requirements fails as the container tag is not a valid version of python when including the sha. This trims the trailing part of the tag to just the [0-9\.]+ part which should be the valid python version.
=> fix: Handle pinned sha versions of Python in the install_requirements action

template/{% if git_platform=="github.com" %}.github{% endif %}/workflows/ci.yml.jinja
Re-fixes the issue in #253 which made modifications to only one of the ci.yaml files and therefore only to this repository's workflows not the workflows of generated repos.
=> fix: Deduplicate jobs from generated workflows

README.md, docs/tutorials/create-new.md
=> docs: Document repo creation method

pyproject.toml, template/pyproject.toml.jinja, tests/test_example.py
Fixes #282
Enable pep8-naming ruff rules, enforcing that projects follow convetional pep8 naming styles. See https://peps.python.org/pep-0008
=> feat: Enable pep8-naming ruff rules

template/Dockerfile.jinja
Fixes https://github.com/DiamondLightSource/python-copier-template/issues/288
Separatet COPY/chmod line into two separate commands so the Dockerfile can be build locally by buildah (podman) as well as CI.
=> fix: Remove requirement for buildkit
